# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-08-21 11:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=144)),
                ('order', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=144)),
                ('name', models.CharField(max_length=144)),
                ('count', models.IntegerField()),
                ('limit', models.IntegerField()),
            ],
        ),
    ]
